package Day67;

// Leetcode Problem 389 

// Find the Difference

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// My Solution
class Solution {
    public char findTheDifference(String s, String t) {

        int[] frequency = new int[26]; 
        
        char[] a1 = s.toCharArray();
        char[] a2 = t.toCharArray();

        for (char k : a1)
        {
            frequency[k-'a']++;
        }

        for (char e : a2)
        {
            frequency[e-'a']--; 
        }

        for (int i=0;i<a2.length;i++)
        {
            if (frequency[a2[i]-'a']!=0) return a2[i];
        }

        char a = ' ';

        return a;
    }
}

public class Find_the_difference {
    
}
